name: deriv
description: A coding test for Deriv

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  configuration:
    path: ./lib/configuration

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_dotenv: ^5.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  
  internet_connection_checker: ^1.0.0+1

  injectable: ^1.5.3
  get_it: ^7.2.0

  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^4.14.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  injectable_generator: ^1.5.2
  json_serializable: ">4.4.0"
  mockito: ^5.0.10
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
